src/AppBundle/Entity/User.php
<?php

namespace AppBundle\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use AppBundle\Services\ImageResizer;

/**
 * @ORM\Entity
 * @ORM\Table(name="user")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(name="id", type="string", length=40, nullable=false)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class="AppBundle\Doctrine\ORM\Id\Sha1IdGenerator")
     */
    protected $id;

	/**
	 * @ORM\Column(name="firstname", type="string", length=100, nullable=true)
	 * @Assert\Length(
	 *     min=2,
	 *     minMessage="Le prénom devra comporter 2 caractères minimum",
	 * )
	 */

    private $firstname;

    /**
     * @ORM\Column(name="matricule", type="string", length=100, nullable=true)
     * @Assert\Length(
     *     min=7,
     *     max=7,
     *     minMessage="Le matricule devra comporter 7 caractères minimum",
     *     maxMessage="Le matricule devra comporter 7 caractères maximum",
     * )
     */
    private $matricule;

    /**
     * @ORM\Column(name="lastname", type="string", length=50, nullable=true)
     * @Assert\Length(
     *     min=2,
     *     minMessage="Le nom devra comporter 2 caractères minimum",
     * )
     */
    private $lastname;

     /**
     * @Assert\Length(min=4, minMessage="Le mot de passe devrait comporter au minimum 4 caractères")
     * @var string
     */
    protected $plainPassword;

    /**
     * @ORM\ManyToOne(targetEntity="Entite", inversedBy="users")
     * @ORM\JoinColumn(name="entite_id", referencedColumnName="id", onDelete="SET NULL")
     */
    private $entite;

    /**
     * @ORM\OneToMany(targetEntity="Message", mappedBy="userSender")
     */
    private $message;

    // /**
    //  * @ORM\OneToMany(targetEntity="ActivityLog", mappedBy="user")
    //  */
    // private $activityLog;

    /**
     * @var string
     *
     * @ORM\Column(name="photo", type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @Assert\File(
     *     mimeTypes={"image/jpeg", "image/png", "image/jpg"},
     *     mimeTypesMessage = "Le type de fichier est invalide",
     * )
     */
    private $filePhoto;

    public $toDelete = array();
    
    /**
     * Constant for path of directory's media image
     */
    const THUMB_PATH = 'uploads/images/photoProfil';

    private $temp;

    public function __construct()
    {
        parent::__construct();
        // your own logic
    }

    /**
     * Set photo
     *
     * @param string $photo
     *
     * @return AbstractUser
     */
    public function setPhoto($photo)
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * Get photo
     *
     * @return string
     */
    public function getPhoto()
    {
        return $this->photo;
    }
    
    /**
     * @return File
     */
    public function getFilePhoto()
    {
        return $this->filePhoto;
    }

    /**
     * @param \Symfony\Component\HttpFoundation\File\UploadedFile $filePhoto
     */
    public function setFilePhoto(UploadedFile $filePhoto = null)
    {
        if (null != $filePhoto) {
            if (!is_null($this->photo)) {
                array_push($this->toDelete, $this->photo);
            }
            $this->photo = $this->performFileName($filePhoto);
            $this->filePhoto = $filePhoto;
        }
    }

    /**
     * @return null|string
     */
    public function getAbsolutePath()
    {
        return $this->getUploadRootDir().'/';
    }

    public function getWebPath()
    {
        return $this->getUploadDir().'/';
    }

    protected function getUploadRootDir()
    {
        return __DIR__.'/../../../web/'.$this->getUploadDir();
    }

    protected function getUploadDir()
    {
        return self::THUMB_PATH;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        if (null === $this->getPhoto()) {
            return;
        }
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        if (null !== $this->getFilePhoto()) {
            $this->uploadFile($this->filePhoto, 'photo');
        }
        $this->toDelete = array();
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUploadedPhoto()
    {
        $this->toDelete = [$this->getPhoto()];
        foreach ($this->toDelete as $f) {
            if ( $file = $this->getAbsolutePath() . $f ) {
                if (!\is_dir($file) && \file_exists($file) ) {
                    unlink($file);
                }
            }
        }
    }
    /**
     * @param File $file
     */
    private function uploadFile($file, $field)
    {
        $file->move($this->getUploadRootDir(), $file->getClientOriginalName());
        $image = $this->getUploadRootDir().'/'.$file->getClientOriginalName();
        if ($field=='photo') {
            $this->$field = ImageResizer::resizeImage($image, $this->getUploadRootDir(), 840, 420, $this->$field);
        }
            // } else if ($field=='photo2'){
        //     $this->$field = ImageResizer::resizeImage($image, $this->getUploadRootDir(), 840, 420, $this->$field);
        // } else {
        //     $this->$field = ImageResizer::resizeImage($image, $this->getUploadRootDir(), 0, 0, $this->$field);
        // }
  
        if (isset($this->temp)) {
            unlink($this->getUploadRootDir().'/'.$this->temp);
            $this->temp = null;
        }
        unlink($image);
        $file = null;
    }

    /**
     * @param $file
     *
     * @return string
     */
    private function performFileName($file)
    {
        return sha1(uniqid(mt_rand(), true)).'.'.$file->guessExtension();
    }

    /**
     * Set firstname
     *
     * @param string $firstname
     *
     * @return User
     */
    public function setFirstname($firstname)
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * Get firstname
     *
     * @return string
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * Set lastname
     *
     * @param string $lastname
     *
     * @return User
     */
    public function setLastname($lastname)
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * Get lastname
     *
     * @return string
     */
    public function getLastname()
    {
        return $this->lastname;
    }

     /**
     * @param string $email
     * @return $this
     */
    public function setEmail($email)
    {
        $email = is_null($email) ? '' : $email;
        parent::setEmail($email);
        // $this->setUsername($email);

        return $this;
    }

    /**
     * Set entite
     *
     * @param \AppBundle\Entity\Entite $entite
     *
     * @return User
     */
    public function setEntite(\AppBundle\Entity\Entite $entite = null)
    {
        $this->entite = $entite;

        return $this;
    }

    /**
     * Get entite
     *
     * @return \AppBundle\Entity\Entite
     */
    public function getEntite()
    {
        return $this->entite;
    }

    /**
     * Add message
     *
     * @param \AppBundle\Entity\Message $message
     *
     * @return User
     */
    public function addMessage(\AppBundle\Entity\Message $message)
    {
        $this->message[] = $message;

        return $this;
    }

    /**
     * Remove message
     *
     * @param \AppBundle\Entity\Message $message
     */
    public function removeMessage(\AppBundle\Entity\Message $message)
    {
        $this->message->removeElement($message);
    }

    /**
     * Get message
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Set matricule
     *
     * @param string $matricule
     *
     * @return User
     */
    public function setMatricule($matricule)
    {
        $this->matricule = $matricule;

        return $this;
    }

    /**
     * Get matricule
     *
     * @return string
     */
    public function getMatricule()
    {
        return $this->matricule;
    }

    // /**
    //  * Add activityLog
    //  *
    //  * @param \AppBundle\Entity\ActivityLog $activityLog
    //  *
    //  * @return User
    //  */
    // public function addActivityLog(\AppBundle\Entity\ActivityLog $activityLog)
    // {
    //     $this->activityLog[] = $activityLog;

    //     return $this;
    // }

    // /**
    //  * Remove activityLog
    //  *
    //  * @param \AppBundle\Entity\ActivityLog $activityLog
    //  */
    // public function removeActivityLog(\AppBundle\Entity\ActivityLog $activityLog)
    // {
    //     $this->activityLog->removeElement($activityLog);
    // }

    // /**
    //  * Get activityLog
    //  *
    //  * @return \Doctrine\Common\Collections\Collection
    //  */
    // public function getActivityLog()
    // {
    //     return $this->activityLog;
    // }
}

src/AppBundle/Controller/UserController.php
<?php

namespace AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use AppBundle\Entity\User;
use AppBundle\Form\UserType;
use AppBundle\Form\UserTypeEdit;
use AppBundle\Services\Log;
use Symfony\Component\HttpFoundation\JsonResponse;

/**
 * @Route("/adminarssam")
 */
class UserController extends Controller
{
    /**
     * @Route("/user", name="arssam_user_list")
     */
    public function indexAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $search = [];
        $user = $this->getUser();
        
        if(!$user->hasRole('ROLE_SUPER_ADMIN')){
            $entite = $user->getEntite();
            $search['entiteId'] = $entite->getId();
        }
        if($user->hasRole('ROLE_OFFICIER')){
            $search['onlyMe'] = $user->getId();
        }
        // $users = $em->getRepository('AppBundle:User')->getUserByFilters($search);
        $users = $em->getRepository('AppBundle:User')->getQueryUserByFilters($search);
        // $paginator  = $this->get('knp_paginator');
        // $users = $paginator->paginate(
        //     $query, 
        //     $request->query->getInt('page', 1),2
        // );
        return $this->render('@App/User/index.html.twig',['users'=>$users]);
    }

    /**
     * @Route("/user/add", name="arssam_user_create")
     */
    public function createAction(Request $request, Log $actLog)
    {
        $userConected = $this->getUser();
        $user = new User();
        $em = $this->getDoctrine()->getManager();
        $form = $this->createForm(UserType::class,$user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
           $data = $request->request->get('appbundle_user');
           $user->addRole($data['roles']);
           /** create username */
           $name = $data['lastname'];
           $firstname = $data['firstname']; 
        //    $username = $firstname[0].$firstname[strlen($firstname)-1].".".$name;
           $username = $firstname[0].$firstname[1].".".$name;
           $user->setUsername($username);
           /** end */
           /** assign role & entite */
           if($userConected->hasRole('ROLE_FOCAL')){
               $user->setEntite($userConected->getEntite());
               $user->setRoles(['ROLE_OFFICIER']);
           }
           /** end */
           $em->persist($user);
           $em->flush();  
           /** ADD LOG */
        //    $log = [];
        //    $log['user'] = $userConected;
        //    $log['action'] = 'CREATE';
        //    $log['description'] = 'Nouvelle utilisateur';
        //    $log['entityId'] = $user->getId();
        //    $log['entityName'] = 'user';
        //    $actLog->addLog($log);
           /** end  */  
        $this->addFlash('success','Opération effectuée avec succès');
        return $this->redirectToRoute('arssam_user_list');
        }
        return $this->render('AppBundle:User:create.html.twig', array(
            'form' => $form->createView(),
        ));
    }

    /**
     * @Route("/user/edit/{id}", name="arssam_user_edit")
     */
    public function updateAction($id,Request $request, Log $actLog)
    {
        $userConected = $this->getUser();
        $em = $this->getDoctrine()->getManager();
        $user = $em->getRepository('AppBundle:User')->find($id);
        $form = $this->createForm(UserTypeEdit::class,$user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
           $role = $request->request->get('role');
           $data = $request->request->get('appbundle_user_edit');
            /** create username */
            $name = $data['lastname'];
            $firstname = $data['firstname']; 
            // $username = $firstname[0].$firstname[strlen($firstname)-1].".".$name;
            $username = $firstname[0].$firstname[1].".".$name;
            $user->setUsername($username);           
           $user->setRoles([$role]);
           $em->persist($user);
           $em->flush();   
           /** ADD LOG */
        //    $log = [];
        //    $log['user'] = $userConected;
        //    $log['action'] = 'UPDATE';
        //    $log['description'] = 'Modification utilisateur';
        //    $log['entityId'] = $user->getId();
        //    $log['entityName'] = 'user';
        //    $actLog->addLog($log);
           /** end  */  
           $this->addFlash('success','Opération effectuée avec succès');   
           return $this->redirectToRoute('arssam_user_list');
        }
        $listRoles = ['ROLE_SUPER_ADMIN'=> 'Super Admin','ROLE_FOCAL'=> 'Point focal', 'ROLE_OFFICIER'=>'Officier de liaison'];
        return $this->render('AppBundle:User:update.html.twig', array(
            'form' => $form->createView(),
            'user' => $user,
            'listRoles' => $listRoles
        ));
    }
    /**
     * @Route("/user/delete/{id}", name="arssam_user_delete")
     */
    public function deleteAction($id,Request $request, Log $actLog)
    {
        $em = $this->getDoctrine()->getManager();
        $userConected = $this->getUser();
        $user = $em->getRepository('AppBundle:User')->find($id);
        /** ADD LOG */
        // $log = [];
        // $log['user'] = $userConected;
        // $log['action'] = 'DELETE';
        // $log['description'] = 'Suppression/Désactivation utilisateur '.$user->getFirstname().' '.$user->getLastname();
        // $log['entityId'] = $user->getId();
        // $log['entityName'] = 'user';
        // $actLog->addLog($log);
        /** end  */ 
        $user->setEnabled(false);
        $em->flush();
        $this->addFlash('success','Opération effectuée avec succès');
        return $this->redirectToRoute('arssam_user_list');
        
    }

    /**
     * @Route("/user/reactive/{id}", name="arssam_user_reactive")
     */
    public function reactiveAction($id,Request $request, Log $actLog)
    {
        $em = $this->getDoctrine()->getManager();
        $userConected = $this->getUser();
        $user = $em->getRepository('AppBundle:User')->find($id);
        /** ADD LOG */
        // $log = [];
        // $log['user'] = $userConected;
        // $log['action'] = 'DELETE';
        // $log['description'] = 'Suppression/Désactivation utilisateur '.$user->getFirstname().' '.$user->getLastname();
        // $log['entityId'] = $user->getId();
        // $log['entityName'] = 'user';
        // $actLog->addLog($log);
        /** end  */ 
        $user->setEnabled(true);
        $em->flush();
        $this->addFlash('success','Opération effectuée avec succès');
        return $this->redirectToRoute('arssam_user_list');
        
    }
    /**
     * @Route ("/user/delete-photo", name="arssam_user_delete_photo")
     * */
    public function deletePhotoAction(Request $request){
        $em = $this->getDoctrine()->getManager();
        $id = $request->request->get('userId');
        $user = $em->getRepository('AppBundle:User')->find($id);
        $user->setPhoto(null);
        $em->flush();
        return new JsonResponse(['success'=>true]);
    }
}

src/AppBundle/Resources/views/User/create.html.twig
{% extends '::base.html.twig' %}

{% block header %}
    <h1>
        Utilisateur
    </h1>
{% endblock %}

{% block content %}
    {% embed ':Embed:box.html.twig' %}
        {% block title %}
            <i class="fa fa-plus-circle"></i>
            Création utilisateur
        {% endblock %}
        {% block boxContent %}
            <form action="{{ path('arssam_user_create') }}" method="post" class="form-horizontal" enctype ="multipart/form-data">
                <i class="validateTips">Tous les champs avec un astérisque (<span class="form-required" title="Ce champ est requis."> * </span>) sont obligatoires</i><br><br>
                <div class="form-group {% if form.matricule.vars.errors|length %}has-error {% endif %}">
                    <label class="col-sm-2  ">{{ form_label(form.matricule) }} </label>
                    <div class="col-sm-10">
                        {{ form_widget(form.matricule, { 'attr': {'class': 'form-control'} }) }}
                        {{ form_errors(form.matricule) }}
                    </div>
                </div>
                <div class="form-group {% if form.lastname.vars.errors|length %}has-error {% endif %}">
                    <label class="col-sm-2  ">{{ form_label(form.lastname) }} <span class="form-required" title="Ce champ est requis.">*</span></label>
                    <div class="col-sm-10">
                        {{ form_widget(form.lastname, { 'attr': {'class': 'form-control'} }) }}
                        {{ form_errors(form.lastname) }}
                    </div>
                </div>

                <div class="form-group {% if form.firstname.vars.errors|length %}has-error {% endif %}">
                    <label class="col-sm-2  ">{{ form_label(form.firstname) }} <span class="form-required" title="Ce champ est requis.">*</span></label>
                    <div class="col-sm-10">
                        {{ form_widget(form.firstname, { 'attr': {'class': 'form-control'} }) }}
                        {{ form_errors(form.firstname) }}
                    </div>
                </div>

                {# <div class="form-group {% if form.username.vars.errors|length %}has-error {% endif %}">
                    <label class="col-sm-2  ">{{ form_label(form.username) }}</label>
                    <div class="col-sm-10">
                        {{ form_widget(form.username, { 'attr': {'class': 'form-control'} }) }}
                        {{ form_errors(form.username,{'attr':{'class':'form-error'}}) }}
                    </div>
                </div> #}

                <div class="form-group {% if form.email.vars.errors|length %}has-error {% endif %}">
                    <label class="col-sm-2  ">{{ form_label(form.email) }} <span class="form-required" title="Ce champ est requis.">*</span></label>
                    <div class="col-sm-10">
                        {{ form_widget(form.email, { 'attr': {'class': 'form-control'} }) }}
                        {{ form_errors(form.email) }}
                    </div>
                </div>

                <div class="form-group {% if form.plainPassword.first.vars.errors|length %}has-error {% endif %}">
                    <label class="col-sm-2 ">{{ form_label(form.plainPassword.first) }} <span class="form-required" title="Ce champ est requis.">*</span></label>
                    <div class="col-sm-10">
                        {{ form_widget(form.plainPassword.first, { 'attr': {'class': 'form-control'} }) }}
                        {{ form_errors(form.plainPassword.first) }}
                    </div>
                </div>

                <div class="form-group {% if form.plainPassword.second.vars.errors|length %}has-error {% endif %}">
                    <label class="col-sm-2   ">{{ form_label(form.plainPassword.second) }} <span class="form-required" title="Ce champ est requis.">*</span></label>
                    <div class="col-sm-10">
                        {{ form_widget(form.plainPassword.second, { 'attr': {'class': 'form-control'} }) }}
                        {{ form_errors(form.plainPassword.second) }}
                    </div>
                </div>
                {% if is_granted('ROLE_SUPER_ADMIN') %}
                    <div class="form-group {% if form.roles.vars.errors|length %}has-error {% endif %}">
                        <label class="col-sm-2  ">{{ form_label(form.roles) }}</label>
                        <div class="col-sm-10">
                            {{ form_widget(form.roles, { 'attr': {'class': 'form-control'} }) }}
                            {{ form_errors(form.roles) }}
                        </div>
                    </div>
                
                    <div class="form-group {% if form.entite.vars.errors|length %}has-error {% endif %}">
                        <label class="col-sm-2  ">{{ form_label(form.entite) }}</label>
                        <div class="col-sm-10">
                            {{ form_widget(form.entite, { 'attr': {'class': 'form-control'} }) }}
                            {{ form_errors(form.entite) }}
                        </div>
                    </div>
                {% endif %}
                <div class="form-group {% if form.enabled.vars.errors|length %}has-error {% endif %}">
                    <label class="col-sm-2  ">{{ form_label(form.enabled) }}</label>
                    <div class="col-sm-10">
                        {{ form_widget(form.enabled, { 'attr': {'class': ''} }) }}
                        {{ form_errors(form.enabled) }}
                    </div>
                </div>


                {# <div class="form-group {% if form.repertoire.vars.errors|length %}has-error {% endif %}">
                    <label class="col-sm-2  ">{{ form_label(form.repertoire) }}</label>
                    <div class="col-sm-10">
                        {{ form_widget(form.repertoire, { 'attr': {'class': ''} }) }}
                        {{ form_errors(form.repertoire) }}
                    </div>
                </div> #}

                {# <div class="form-group">
                    <label class="col-sm-2  ">{{ form_label(form.filePhoto) }}</label>
                    <div class="col-sm-6">
                    {{ form_widget(form.filePhoto, {'attr': {'accept': 'image/*'}}) }}
                    <p class="note-image"><small>Note: Ajouter une photo au format jpg / jpeg / png</small></p>
                    </div>
                </div> #}
                <div class="form-group">
                    <label class="col-sm-2">
                        {{ form_label(form.filePhoto) }}
                    </label>
                    <div class="col-sm-6">
                        <div class="fileinput fileinput-new" data-provides="fileinput">
                            <div class="fileinput-new thumbnail" style="width: 100px; height: 100px;">
                                <img class="imageSource" data-src="holder.js/100%x100%" src="{{ asset(default_photo) }}" alt="">
                            </div>
                            <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 100px; max-height: 100px;">
                               {# {% if praticien is defined and praticien.photo is not null %}
                                    <img class="imageSource" style="width: 100px; height: auto" data-src="holder.js/100%x100%" src="{{ asset(praticien.webPath ~ praticien.photo) }}" alt="">
                                {% endif %}#}
                            </div>
                            <div>
                                <span class="btn btn-default btn-file btn-flat">
                                    <span class="fileinput-new">Choisir une image</span>
                                    <span class="fileinput-exists">Changer</span>
                                    {{ form_widget(form.filePhoto, {'attr': {'accept': 'image/*'}}) }}
                                </span>
                                <a href="#"  class="btn btn-warning" data-dismiss="fileinput">Supprimer</a>
                            </div>
                        </div>
                        <p class="note-image"><small>Note: Ajouter une photo au format jpg / jpeg / png</small></p>
                    </div>
                    <div class="col-sm-4">
                        {{ form_errors(form.filePhoto) }}
                    </div>
                </div>

                {% import ':Macro:buttons.html.twig' as buttons %}
                {% import ':Macro:formButtons.html.twig' as formButtons %}
                {{ formButtons.create() }}
                {{ buttons.back({
                    url : path('arssam_user_list'),
                }) }}

                <div class="hide">
                    {{ form_rest(form) }}
                </div>
            </form>
        {% endblock %}
    {% endembed %}
{% endblock %}

src/AppBundle/Resources/views/User/index.html.twig
{% extends 'base.html.twig' %}
{% block header %}
    <h1>
       Utilisateur
    </h1>
{% endblock %}

{% block content %}
 {% embed 'Embed/box.html.twig' %}
		 {% block title %}
            <i class="fa fa-list"></i>
            Liste des utilisateurs
         {% endblock %}
        {% block boxContent %}
            <div class="form-filter">
                <div class="col-md-8"></div>
                <div class="col-md-4">
                    {% import ':Macro:buttons.html.twig' as buttons %}
                    <div class="pull-right">
                        {{ buttons.create({
                            url: path('arssam_user_create')
                        }) }}
                    </div>
                </div>
            </div>
            {% from '@App/User/macros.html.twig' import list  %}
            {% import ':Macro:misc.html.twig' as misc %}
            {{ list(users) }}
            {% endblock %}
    {% endembed %}
{% endblock %}

src/AppBundle/Resources/views/User/macros.html.twig
{% macro list(users) %}
    {% import ':Macro:alerts.html.twig'  as alerts      %}
    {% import ':Macro:buttons.html.twig' as buttons     %}
    {% import ':Macro:misc.html.twig'    as misc        %}

    {% if users|length > 0 %}
        <table id="users" class="table table-datatable do-datatable">
            <thead>
            <tr>
                {#<th class="text-center">{{ sylius_resource_sort('id', 'pomp.id'|trans) }}</th>#}
                <th class="text-center">Nom</th>
                <th class="text-center">Prénom</th>
                <th class="text-center">Matricule</th>
                <th class="text-center">Nom d'utilisateur</th>
                <th class="text-center">Role</th>
                {#<th class="text-center">{{ sylius_resource_sort('lastLogin', 'pomp.last_login'|trans) }}</th>#}
                <th class="text-center">Status</th>
                <th class="text-center">Entité</th>
                <th class="text-center">Photo de profil</th>
                <th class="text-center">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for user in users %}
                <tr id="{{ user.id }}">
                    {#<td>
                        <a href="{{ path('pomp_user_index', {'id': user.id}) }}">
                            {{ user.id }}
                        </a>
                    </td>#}
                    
                    <td>{{ user.lastname }}</td>
                    <td>{{ user.firstname }}</td>
                    <td>{{ user.matricule }}</td>
                    <td>{{ user.username }}</td>
                    {# <td>{{ user.phone }}</td> #}
                    <td>{{ display_role(user) }}</td>
                    {# <td>{{dump(user.roles)}}</td> #}
                    {#<td>{% if user.lastLogin is not null%}{{ user.lastLogin|date('d/m/Y') }}{% endif %}</td>#}
                    <td>{{ misc.actif_label(user.enabled) }}</td>
                    <td>{% if user.entite %}{{ user.entite.abreviation }}{%else%}-{%endif%}</td>
                    <td>
                        {% if user.photo is defined and user.photo != '' %}
                            <div class="col-sm-offset-2" id="pdp">
                                <p>
                                    {#<img src="http://localhost{% if asset('') != "/" %}{{asset('')}}{% endif %}uploads/images/{{ user.photo }}" width="100" />#}
                                    <img src="{{ asset('uploads/images/photoProfil/'~user.photo) }}" alt="pdp" width="100">
                                <p>
                            </div>
                        {% endif %}
                    </td>
                    <td>
                        {{ buttons.update({ url :path('arssam_user_edit', {'id': user.id}) }) }}
                        {% if app.user.id != user.id %}
                        {% if user.enabled %}
                            {{ buttons.delete({ url: path('arssam_user_delete', {'id': user.id}) }) }}
                        {% else %}
                            <a class="btn btn-success" href="{{ path('arssam_user_reactive', {'id': user.id}) }}">
                                <i class="fa fa-unlock-alt"> 
                                </i>
                                 Réactiver
                            </a>
                        {% endif %}
                    {% endif %}    
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {# <div class="navigation">
            {{ knp_pagination_render(users) }}
        </div> #}
    {% else %}
        {# <hr> #}
        {{ alerts.info('Pas de résultat') }}
    {% endif %}
{% endmacro %}